name: Bookeo Calendar Scraper

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 7:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Decode Google Service Account JSON
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

    - name: Run script
      run: |
        python scripts/cloud_extract_calendar.py
